### ISSUE TITLE
v0.4.0/ intro abstraction layer to tools + client SDK

### ISSUE THREAD

**Issue by dehypnosis** [fragmetric-labs/fragmetric-contracts#169]
(draft)

## additional hierarchy to playground
- [x] let current restaking playground be not aware of fragSOL, nSOL or jito blabla.., rather receives "receipt_token, normalized_token, blabla" from construct
- [x] create a playground of higher level like FragSOLPlayground which inherits RestakingPlayground
- [x] inject fragSOL into the REPL context

## group related features and data
- [x] organized known address.... or metadata... target configurations.. blabla

## Client SDK
- [x] https://www.npmjs.com/package/@fragmetric-labs/sdk

### TODO:
- [x] ledger adapter for node
- [x] state cache & dedupe promise for browser,node
- [x] deposit methods
- [x] pricing methods
- [x] update examples
- [x] publish & version up test and readme
- [ ] playground(? .. = REPL + wrapper functions (?) for testing and operation? or just into sdk?)
- [x] fragSOL, fragJTO playgrounds...
- [ ] other all operation methods
- [ ] snapshot feature for some stuffs.. for fixture based testin
- [ ] testing/playground migration...
- [ ] update keychain stuff.. and aws secret.. readme..
